### ISSUE TITLE
Inquiry about MCP2025 and Possible Alternatives

### ISSUE THREAD

**Issue by Nikolein** [samelyuk/volvo-rti-retrofit#2]
Good day,

Where did you purchase the MCP2025 that you use for the steering wheel buttons? Are there alternatives such as the MCP2515?

Best regards,
Niko de Vries

**Comment by sxcode-git** [comment]
Hello, 
I bought the MCP 2025 on tme.eu . You can also use the MCP 2003 or other LIN bus transceiver. The MCP 2515 is for the CAN bus.

**Comment by Nikolein** [comment]
Did you order them in 3.3V or 5V?
