### ISSUE TITLE
Verification of Connections: Car to IC and Arduino

### ISSUE THREAD

**Issue by Nikolein** [samelyuk/volvo-rti-retrofit#3]
Good day,
For the MCP2025-500E/P or MCP2025-330E/P, VBB is Pin 1 of the IC and should be connected to the Arduino Nano. The power supply from the car, which is on Pin 7 of the connector, is connected to the IC’s reset pin. Additionally, the LBus needs to go to the IC, but it is shown connected to the Arduino instead of the car. Is this correct?
MCP2025-500E/P (5V) or MCP2025-330E/P (3.3V)?
![grafik](https://github.com/user-attachments/assets/8ae3fe85-7cdd-4c4c-a0ac-0e5d57b0e400)
![grafik](https://github.com/user-attachments/assets/b86a4317-9972-49e4-8845-99a3ac125194)

**Comment by sxcode-git** [comment]
I have used the MCP 2004, so there is an error. See this guide: https://github.com/laurynas/volvo_linbus

**Comment by Nikolein** [comment]
Please make the necessary adjustments in your project, as there is a risk of confusion due to the different pinout configurations of the MCP2004 and MCP2025

**Comment by sxcode-git** [comment]
Already did it. Sorry for the inconveniences, and thank you for the help.

**Comment by Nikolein** [comment]
It’s all good, please.

**Comment by Nikolein** [comment]
Hello,
Your project is really great, thank you for sharing it with the community. I noticed a small issue, though: In your diagram from the IC to the Arduino, the blue wire is connected to pin 3 of the IC. It should actually be connected to pin 2 (CS) instead of pin 3 (TXE). It would be great if you could correct that.
![grafik](https://github.com/user-attachments/assets/bd771560-19f2-4d7e-90ff-2d6d2b8b6b6b)

**Comment by sxcode-git** [comment]
Thank you for help! I have corrected it.
